'use strict'
// Manual diagnostic only. It cannot export or admit a runtime candidate.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path')
const sha=value=>crypto.createHash('sha256').update(value).digest('hex')
function physical(value,directory=false){const resolved=fs.realpathSync.native(path.resolve(value));assert.equal(fs.statSync(resolved).isDirectory(),directory);return resolved}
function run(command,args,options={}){const result=cp.spawnSync(command,args,{encoding:'utf8',windowsHide:true,shell:false,maxBuffer:2*1024*1024,...options});assert.ifError(result.error);return result}
function parseRecords(base64){assert.match(base64,/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/);const bytes=Buffer.from(base64,'base64');assert.ok(bytes.length<=1024*1024&&bytes.toString('base64')===base64);const text=bytes.toString('ascii');assert.equal(Buffer.from(text,'ascii').equals(bytes),true);const records=[];for(const line of text.split('\n')){if(!line)continue;assert.match(line,/^span pid=[1-9][0-9]{0,9} event=(?:3|6) load=0x[0-9a-f]+ eventFile=(?:none|error:[0-9]+|[0-9a-f]{8}:[0-9a-f]{16}) base=0x[0-9a-f]+ allocation=0x[0-9a-f]+ size=0x[0-9a-f]+ state=0x[0-9a-f]+ type=0x[0-9a-f]+ protect=0x[0-9a-f]+$/);records.push(Object.fromEntries(line.split(' ').slice(1).map(field=>field.split('='))))}assert.ok(records.length<=4096);return{bytes,text,records}}
async function main(args){
 assert.equal(args.length,2,'Usage: node run.cjs REPO NEW_OUTPUT');assert.equal(process.platform,'win32');assert.equal(process.arch,'x64')
 const repo=physical(args[0],true),output=path.resolve(args[1]);assert.equal(path.dirname(output),physical(path.dirname(output),true));assert.equal(fs.existsSync(output),false,'fresh output required');fs.mkdirSync(output);require(path.join(repo,'agents/codex/workflow/safe-run-root.js')).ensureWindowsPrivateAcl(output)
 const loader=require(path.join(repo,'agents/codex/workflow/windows-worker-loader.js')),tuple=await loader.captureWorkerTuple(),tupleBefore=loader.describeTuple(tuple),runtime=loader.materializeTuple(tuple,path.join(output,'runtime'))
 assert.equal(tupleBefore.architecture,'x64');assert.equal(runtime.identity,tupleBefore.identity);const native=path.join(repo,'agents/codex/workflow/windows-appcontainer-native.cs'),controller=path.join(repo,'scripts/windows-msys/mapping-proof/source/mapping-controller.cs'),deriver=path.join(repo,'scripts/windows-msys/fork-memory-diagnostic/derive.py')
 const sourceHashes={native:sha(fs.readFileSync(native)),controller:sha(fs.readFileSync(controller)),deriver:sha(fs.readFileSync(deriver))},generated=path.join(output,'generated')
 const python=process.env.pythonLocation?path.join(process.env.pythonLocation,'python.exe'):'python.exe',derive=run(python,[deriver,native,sourceHashes.native,controller,sourceHashes.controller,generated],{cwd:repo,timeout:30000,env:{...process.env}});fs.writeFileSync(path.join(output,'derive.stdout.txt'),derive.stdout||'');fs.writeFileSync(path.join(output,'derive.stderr.txt'),derive.stderr||'');assert.equal(derive.status,0,derive.stderr)
 const manifestBytes=fs.readFileSync(path.join(generated,'manifest.json')),manifest=JSON.parse(manifestBytes);assert.equal(manifest.accepted,false);assert.equal(manifest.originalNativeSha256,sourceHashes.native);assert.equal(manifest.originalControllerSha256,sourceHashes.controller);assert.equal(manifest.deriverSha256,sourceHashes.deriver)
 const system=process.env.SystemRoot;assert.match(system||'',/^[A-Za-z]:\\Windows$/i);const executable=path.join(generated,'fork-memory-controller.exe'),powershell=path.join(system,'System32','WindowsPowerShell','v1.0','powershell.exe')
 const compileCommand='[Environment]::SetEnvironmentVariable("PSModulePath",[IO.Path]::Combine($PSHOME,"Modules"),[EnvironmentVariableTarget]::Process);$ErrorActionPreference="Stop";Add-Type -Path @($env:AP_NATIVE,$env:AP_CONTROLLER) -OutputAssembly $env:AP_OUTPUT -OutputType ConsoleApplication'
 const compile=run(powershell,['-NoLogo','-NoProfile','-NonInteractive','-Command',compileCommand],{cwd:generated,timeout:60000,env:{SystemRoot:system,WINDIR:system,SystemDrive:system.slice(0,2),PATH:path.join(system,'System32'),TEMP:generated,TMP:generated,AP_NATIVE:path.join(generated,'windows-appcontainer-native-diagnostic.cs'),AP_CONTROLLER:path.join(generated,'fork-memory-controller.cs'),AP_OUTPUT:executable}});fs.writeFileSync(path.join(output,'compile.stdout.txt'),compile.stdout||'');fs.writeFileSync(path.join(output,'compile.stderr.txt'),compile.stderr||'');assert.equal(compile.status,0,compile.stderr)
 const mapping=require(path.join(repo,'scripts/windows-msys/mapping-proof/run.cjs')),dllBytes=fs.readFileSync(runtime.msysRuntime.dllPath),dataRva=mapping.pe(dllBytes).dataRva.toString(16),work=path.join(output,'work');fs.mkdirSync(work);require(path.join(repo,'agents/codex/workflow/safe-run-root.js')).ensureWindowsPrivateAcl(work)
 const label='fork-memory',invocation=[runtime.bash,runtime.bashSha256,runtime.msysRuntime.dllPath,runtime.msysRuntime.dllSha256,runtime.msysRuntime.sharedId,dataRva,work,label]
 const observed=run(executable,invocation,{cwd:work,timeout:330000,env:{SystemRoot:system,WINDIR:system,SystemDrive:system.slice(0,2),PATH:path.join(system,'System32'),TEMP:work,TMP:work}});fs.writeFileSync(path.join(output,'controller.stdout.txt'),observed.stdout||'');fs.writeFileSync(path.join(output,'controller.stderr.txt'),observed.stderr||'');assert.equal(observed.status,0,observed.stderr)
 const result=JSON.parse(fs.readFileSync(path.join(work,label+'.json'),'utf8'));assert.equal(result.status,'observed-not-accepted');assert.equal(result.cleanupConfirmed,true);assert.equal(result.bashSha256,runtime.bashSha256);assert.equal(result.msysSha256,runtime.msysRuntime.dllSha256);assert.ok(result.forkMemory&&Number.isInteger(result.forkMemory.events)&&result.forkMemory.events>0&&Number.isInteger(result.forkMemory.processes)&&result.forkMemory.processes>0&&Number.isInteger(result.forkMemory.spans)&&result.forkMemory.spans>=0&&result.forkMemory.spans<=4096)
 const parsed=parseRecords(result.forkMemory.recordsBase64),stderr=Buffer.from(result.stderrBase64,'base64').toString('utf8'),failedPids=[...stderr.matchAll(/child_copy: cygheap read copy failed, 0x0\.\.0x[0-9A-Fa-f]+, done 0, windows pid ([0-9]+), Win32 error 299/g)].map(match=>Number(match[1])),createSpans=parsed.records.filter(record=>record.event==='3'),foreignSpans=parsed.records.filter(record=>record.event==='3'||record.allocation!=='0x800000000'||record.type!=='0x20000'),failedCreateSpans=Object.fromEntries([...new Set(failedPids)].map(pid=>[pid,createSpans.filter(record=>Number(record.pid)===pid)])),failedForeignSpans=Object.fromEntries([...new Set(failedPids)].map(pid=>[pid,foreignSpans.filter(record=>Number(record.pid)===pid)]))
 // A normal initialized cygheap is MEM_PRIVATE with allocation base LOW. A
 // different allocation/type inside the fixed interval is a foreign mapping;
 // correlate it to the exact stderr PID rather than treating all occupancy as
 // a collision.
 const conclusive=result.forkMemory.queryError===0&&!result.forkMemory.overflow&&failedPids.length>0&&Object.values(failedForeignSpans).every(records=>records.length>0),classification=conclusive?'foreign-cygheap-range-allocation-correlated-to-every-failed-child':'inconclusive'
 assert.equal(loader.revalidateTuple(tuple).identity,tupleBefore.identity);assert.deepEqual({native:sha(fs.readFileSync(native)),controller:sha(fs.readFileSync(controller)),deriver:sha(fs.readFileSync(deriver))},sourceHashes);assert.equal(sha(fs.readFileSync(runtime.bash)),runtime.bashSha256);assert.equal(sha(fs.readFileSync(runtime.msysRuntime.dllPath)),runtime.msysRuntime.dllSha256)
 const summary={schema:1,status:'observed-not-accepted',accepted:false,classification,tuple:tupleBefore,sourceHashes,derivedManifestSha256:sha(manifestBytes),derivedManifest:manifest,controllerSha256:sha(fs.readFileSync(executable)),runtime:{bashSha256:runtime.bashSha256,dllSha256:runtime.msysRuntime.dllSha256,sharedId:runtime.msysRuntime.sharedId},launch:{exitCode:result.launch.exitCode,drained:result.launch.drained,rootImageMatches:result.launch.rootImageMatches,stdoutSha256:sha(Buffer.from(result.stdoutBase64,'base64')),stderrSha256:sha(Buffer.from(result.stderrBase64,'base64'))},forkMemory:{events:result.forkMemory.events,processes:result.forkMemory.processes,loads:result.forkMemory.loads,spans:result.forkMemory.spans,queryError:result.forkMemory.queryError,overflow:result.forkMemory.overflow,recordsSha256:sha(parsed.bytes),failedPids,failedCreateSpanCounts:Object.fromEntries(Object.entries(failedCreateSpans).map(([pid,records])=>[pid,records.length])),failedForeignSpanCounts:Object.fromEntries(Object.entries(failedForeignSpans).map(([pid,records])=>[pid,records.length]))}}
 fs.writeFileSync(path.join(output,'summary.json'),JSON.stringify(summary,null,2)+'\n');process.stdout.write(JSON.stringify(summary)+'\n')
}
if(require.main===module)main(process.argv.slice(2)).catch(error=>{process.stderr.write(String(error.stack||error)+'\n');process.exitCode=1})
module.exports={parseRecords}
