using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Threading;
using System.Threading.Tasks;
public static class ProcessSecurityController {
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern Boolean ConvertStringSecurityDescriptorToSecurityDescriptor(String text,UInt32 revision,out IntPtr descriptor,out UInt32 size);
 [DllImport("advapi32.dll",SetLastError=true)] static extern Boolean GetSecurityDescriptorSacl(IntPtr descriptor,out Boolean present,out IntPtr sacl,out Boolean defaulted);
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode)] static extern UInt32 SetNamedSecurityInfo(String name,Int32 type,UInt32 flags,IntPtr owner,IntPtr group,IntPtr dacl,IntPtr sacl);
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode)] static extern UInt32 GetNamedSecurityInfo(String name,Int32 type,UInt32 flags,out IntPtr owner,IntPtr group,IntPtr dacl,out IntPtr sacl,out IntPtr descriptor);
 [DllImport("advapi32.dll")] static extern UInt32 GetSecurityDescriptorLength(IntPtr descriptor);
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern Boolean ConvertSecurityDescriptorToStringSecurityDescriptor(IntPtr descriptor,UInt32 revision,UInt32 flags,out IntPtr text,out UInt32 length);
 [DllImport("kernel32.dll")] static extern IntPtr LocalFree(IntPtr memory);
 static readonly List<Object> Retained=new List<Object>();
 sealed class Operation { public String Name,Cancel;public Task<WindowsAppContainerNative.LaunchResult> Task;public WindowsAppContainerNative.LaunchResult Result; }
 static void Need(Boolean value,String reason){if(!value)throw new InvalidOperationException(reason);}
 static String Hash(String file){using(var stream=File.OpenRead(file))using(var hash=SHA256.Create())return BitConverter.ToString(hash.ComputeHash(stream)).Replace("-","").ToLowerInvariant();}
 // SACL control flags describe descriptor inheritance state; they are not
 // mandatory-label ACE flags. Require the exact sole label independently of
 // its SDDL serialization, including zero ACE propagation/inherited flags.
 static Boolean ExactLowLabelAcl(Byte[] acl){
  Byte[] expected={2,0,28,0,1,0,0,0,17,0,20,0,1,0,0,0,1,1,0,0,0,0,0,16,0,16,0,0};
  if(acl==null||acl.Length!=expected.Length||(acl[0]!=2&&acl[0]!=4))return false;
  for(Int32 i=1;i<expected.Length;i++)if(acl[i]!=expected[i])return false;
  return true;
 }
 static String LabelDiagnostic(IntPtr descriptor){IntPtr text=IntPtr.Zero;try{UInt32 length;if(descriptor==IntPtr.Zero||!ConvertSecurityDescriptorToStringSecurityDescriptor(descriptor,1,0x10,out text,out length)||text==IntPtr.Zero||length==0||length>1024)return "unavailable";String value=Marshal.PtrToStringUni(text,(Int32)length);if(value!=null&&value.EndsWith("\0",StringComparison.Ordinal))value=value.Substring(0,value.Length-1);return value!=null&&value.IndexOf('\0')<0?value:"unavailable";}finally{if(text!=IntPtr.Zero)LocalFree(text);}}
 static void VerifyLowDirectory(String directory){IntPtr owner=IntPtr.Zero,sacl=IntPtr.Zero,descriptor=IntPtr.Zero;try{
  UInt32 status=GetNamedSecurityInfo(directory,1,0x10,out owner,IntPtr.Zero,IntPtr.Zero,out sacl,out descriptor);
  Need(status==0&&descriptor!=IntPtr.Zero&&sacl!=IntPtr.Zero,"query-low-directory-label:"+status);
  UInt32 size=GetSecurityDescriptorLength(descriptor);Int64 offset=sacl.ToInt64()-descriptor.ToInt64();
  Need(size>=20&&size<=4096&&offset>=20&&offset<=(Int64)size-8,"bounded-low-directory-label");
  Int32 aclSize=unchecked((UInt16)Marshal.ReadInt16(sacl,2));
  if(aclSize!=28||offset>(Int64)size-aclSize)throw new InvalidOperationException("low-directory-label-size:"+aclSize+":"+LabelDiagnostic(descriptor));
  Byte[] bytes=new Byte[aclSize];Marshal.Copy(sacl,bytes,0,bytes.Length);
  if(!ExactLowLabelAcl(bytes))throw new InvalidOperationException("confirmed-low-directory-label:"+LabelDiagnostic(descriptor));
 }finally{if(descriptor!=IntPtr.Zero)LocalFree(descriptor);}}
 static void LowDirectory(String directory){IntPtr sd=IntPtr.Zero,sacl;try{UInt32 size;Boolean present,defaulted;Need(ConvertStringSecurityDescriptorToSecurityDescriptor("S:(ML;;NW;;;LW)",1,out sd,out size),"low-descriptor");Need(GetSecurityDescriptorSacl(sd,out present,out sacl,out defaulted)&&present,"low-sacl");Need(SetNamedSecurityInfo(directory,1,0x10,IntPtr.Zero,IntPtr.Zero,IntPtr.Zero,sacl)==0,"low-directory-label");VerifyLowDirectory(directory);}finally{if(sd!=IntPtr.Zero)LocalFree(sd);}}

 static void DirectoryAcl(String directory,String[] packages,Boolean writable){var user=WindowsIdentity.GetCurrent().User;var sd=new DirectorySecurity();sd.SetOwner(user);sd.SetAccessRuleProtection(true,false);foreach(String sid in new[]{user.Value,"S-1-5-18"})sd.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));foreach(String sid in packages)sd.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),writable?FileSystemRights.Modify:FileSystemRights.ReadAndExecute,writable?InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit:InheritanceFlags.None,PropagationFlags.None,AccessControlType.Allow));new DirectoryInfo(directory).SetAccessControl(sd);if(writable)LowDirectory(directory);}
 static void ExecutableAcl(String executable,String sidA,String sidB){var user=WindowsIdentity.GetCurrent().User;var sd=new FileSecurity();sd.SetOwner(user);sd.SetAccessRuleProtection(true,false);foreach(String sid in new[]{user.Value,"S-1-5-18",sidA,sidB})sd.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),sid==sidA||sid==sidB?FileSystemRights.ReadAndExecute:FileSystemRights.FullControl,AccessControlType.Allow));new FileInfo(executable).SetAccessControl(sd);DirectoryAcl(Path.GetDirectoryName(executable),new[]{sidA,sidB},false);}
 static String[] EnvironmentEntries(){String root=Environment.GetEnvironmentVariable("SystemRoot"),local=Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);Need(!String.IsNullOrEmpty(root)&&!String.IsNullOrEmpty(local)&&Directory.Exists(local),"known-Windows-folders");return new[]{"SystemRoot="+root,"WINDIR="+root,"SystemDrive="+root.Substring(0,2),"PATH="+Path.Combine(root,"System32"),"LOCALAPPDATA="+local};}
 static void ExclusiveMarker(String path,String value){using(var stream=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None)){Byte[] bytes=Encoding.UTF8.GetBytes(value);stream.Write(bytes,0,bytes.Length);stream.Flush(true);}}
 static Operation Start(List<Operation> all,String name,String control,String executable,String digest,String[] arguments,String cwd,String[] env,IntPtr sid,String sidText,Int32 timeout,WindowsAppContainerNative.MsysNamespaceRequest msys=null){var operation=new Operation{Name=name,Cancel=Path.Combine(control,"cancel-"+name)};Need(!File.Exists(operation.Cancel),"fresh-cancellation");all.Add(operation);operation.Task=Task.Factory.StartNew(()=>WindowsAppContainerNative.Launch(executable,digest,arguments,cwd,env,timeout,16384,sid,sidText,operation.Cancel,msys),CancellationToken.None,TaskCreationOptions.LongRunning,TaskScheduler.Default);return operation;}
 static WindowsAppContainerNative.LaunchResult Complete(Operation operation,Int32 timeout){Need(operation.Task.Wait(timeout),operation.Name+"-controller-wait");var result=operation.Task.GetAwaiter().GetResult();operation.Result=result;Need(result.Drained&&!result.TimedOut&&!result.Cancelled&&!result.OutputLimit&&result.RootImageMatches,operation.Name+"-owned-drain-and-identity");Need(result.ExitCode==0,operation.Name+"-exit:"+result.ExitCode+":"+Encoding.UTF8.GetString(Convert.FromBase64String(result.StderrBase64)));Need(result.StderrBase64=="",operation.Name+"-unexpected-stderr");return result;}
 static Boolean DrainAll(List<Operation> all){Boolean confirmed=true;foreach(var operation in all)if(operation.Task!=null&&!operation.Task.IsCompleted){try{ExclusiveMarker(operation.Cancel,"cancel\n");}catch(IOException){if(!File.Exists(operation.Cancel))confirmed=false;}}var clock=Stopwatch.StartNew();foreach(var operation in all){if(operation.Task==null)continue;try{Int32 remaining=(Int32)Math.Max(0,7000-clock.ElapsedMilliseconds);if(!operation.Task.Wait(remaining)){confirmed=false;continue;}operation.Result=operation.Task.GetAwaiter().GetResult();if(!operation.Result.Drained)confirmed=false;}catch{confirmed=false;}}return confirmed;}


 [DllImport("kernel32.dll",SetLastError=true)] static extern IntPtr OpenProcess(UInt32 access,Boolean inherit,UInt32 id);
 [DllImport("kernel32.dll",SetLastError=true)] static extern IntPtr OpenThread(UInt32 access,Boolean inherit,UInt32 id);
 [DllImport("kernel32.dll",SetLastError=true)] static extern UInt32 GetProcessIdOfThread(IntPtr thread);
 [DllImport("kernel32.dll",SetLastError=true)] static extern UInt32 WaitForSingleObject(IntPtr handle,UInt32 timeout);
 [DllImport("kernel32.dll")] static extern Boolean CloseHandle(IntPtr handle);
 [DllImport("advapi32.dll",SetLastError=true)] static extern Boolean GetKernelObjectSecurity(IntPtr handle,UInt32 flags,Byte[] descriptor,UInt32 length,out UInt32 needed);
 static UInt32[] Ready(Operation creator,String path){var clock=Stopwatch.StartNew();for(;;){if(File.Exists(path)){try{Need((File.GetAttributes(path)&(FileAttributes.ReparsePoint|FileAttributes.Directory))==0,"ready-physical-file");using(var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)){Need(stream.Length>=4&&stream.Length<=22,"ready-length");Byte[] bytes=new Byte[(Int32)stream.Length];Need(stream.Read(bytes,0,bytes.Length)==bytes.Length,"ready-complete");String text=Encoding.ASCII.GetString(bytes);var match=System.Text.RegularExpressions.Regex.Match(text,@"\A([1-9][0-9]{0,9}) ([1-9][0-9]{0,9})\n\z");UInt32 pid,tid;Need(match.Success&&UInt32.TryParse(match.Groups[1].Value,out pid)&&UInt32.TryParse(match.Groups[2].Value,out tid),"ready-identities");return new[]{UInt32.Parse(match.Groups[1].Value),UInt32.Parse(match.Groups[2].Value)};}}catch(IOException error){Int32 code=error.HResult&0xffff;if(code!=32&&code!=33)throw;}}Need(!creator.Task.IsCompleted,"creator-exited-before-ready");Need(clock.ElapsedMilliseconds<15000,"ready-deadline");Thread.Sleep(10);}}
 static Byte[] Security(IntPtr handle,String user,String package){Byte[] data=new Byte[16384];UInt32 needed;Need(GetKernelObjectSecurity(handle,0x17,data,(UInt32)data.Length,out needed)&&needed>=20&&needed<=data.Length,"bounded-process-security");Array.Resize(ref data,(Int32)needed);var sd=new RawSecurityDescriptor(data,0);Need(sd.Owner!=null&&sd.DiscretionaryAcl!=null&&sd.DiscretionaryAcl.Count==5,"exact-owned-child-descriptor");String[] sids={user,"S-1-5-11","S-1-5-32-544","S-1-5-18",package};for(Int32 i=0;i<5;i++){var ace=sd.DiscretionaryAcl[i] as CommonAce;Need(ace!=null&&ace.AceType==AceType.AccessAllowed&&ace.AceFlags==AceFlags.None&&ace.SecurityIdentifier.Value==sids[i]&&unchecked((UInt32)ace.AccessMask)==(i==1?0x1000u:0x1fffffu),"exact-preserved-child-ace-"+i);}
 // Label flags may be object-specific; retain their exact bytes and require
 // low integrity plus no-write-up, without inventing a universal label mask.
 Need(sd.SystemAcl!=null&&sd.SystemAcl.Count==1,"one-child-mandatory-label");var label=sd.SystemAcl[0];Byte[] raw=new Byte[label.BinaryLength];label.GetBinaryForm(raw,0);Need(raw.Length==20&&raw[0]==17&&raw[1]==0&&(BitConverter.ToUInt32(raw,4)&1)==1&&(BitConverter.ToUInt32(raw,4)&~7u)==0&&new SecurityIdentifier(raw,8).Value=="S-1-16-4096","low-child-label");return data;}
 static String Shell(String value){return "'"+value.Replace("'","'\\''")+"'";}
 public static Int32 Main(String[] args){var operations=new List<Operation>();IntPtr sidA=IntPtr.Zero,sidB=IntPtr.Zero,process=IntPtr.Zero,thread=IntPtr.Zero;String nameA="Autoprompt_"+Guid.NewGuid().ToString("N"),nameB="Autoprompt_"+Guid.NewGuid().ToString("N");Boolean createdA=false,createdB=false,drained=true;String proof=null;Exception failure=null;
 try{Need(args.Length==10,"arguments: fixture digest bash digest dll digest shared-id control cwd-A cwd-B");String executable=Path.GetFullPath(args[0]),bash=Path.GetFullPath(args[2]),dll=Path.GetFullPath(args[4]),control=Path.GetFullPath(args[7]),cwdA=Path.GetFullPath(args[8]),cwdB=Path.GetFullPath(args[9]);Need(Hash(executable)==args[1]&&Hash(bash)==args[3]&&Hash(dll)==args[5],"bound-inputs");String communications=Path.Combine(cwdA,"communications");Directory.CreateDirectory(communications);String ready=Path.Combine(communications,"ready"),release=Path.Combine(communications,"release");
 Need(WindowsAppContainerNative.CreateAppContainerProfile(nameA,nameA,nameA,IntPtr.Zero,0,out sidA)>=0,"create-A");createdA=true;Need(WindowsAppContainerNative.CreateAppContainerProfile(nameB,nameB,nameB,IntPtr.Zero,0,out sidB)>=0,"create-B");createdB=true;String a=new SecurityIdentifier(sidA).Value,b=new SecurityIdentifier(sidB).Value;Need(a!=b,"distinct-profiles");foreach(String file in new[]{executable,bash,dll})ExecutableAcl(file,a,b);String bin=Path.GetDirectoryName(bash),usr=Path.GetDirectoryName(bin),runtime=Path.GetDirectoryName(usr);Need(Path.GetFileName(bin)=="bin"&&Path.GetFileName(usr)=="usr","private-msys-layout");DirectoryAcl(usr,new[]{a,b},false);DirectoryAcl(runtime,new[]{a,b},false);String etc=Path.Combine(runtime,"etc");DirectoryAcl(etc,new[]{a,b},false);ExecutableAcl(Path.Combine(etc,"fstab"),a,b);
 DirectoryAcl(cwdA,new[]{a},false);DirectoryAcl(cwdB,new[]{b},false);DirectoryAcl(communications,new[]{a},true);var env=EnvironmentEntries().Concat(new[]{"TEMP="+communications,"TMP="+communications,"MSYSTEM=MINGW64","CHERE_INVOKING=1"}).ToArray();var request=new WindowsAppContainerNative.MsysNamespaceRequest{DllPath=dll,DllSha256=args[5],SharedId=args[6]};
 String script=Shell(executable.Replace('\\','/'))+" hold "+Shell(a)+" "+Shell(ready.Replace('\\','/'))+" "+Shell(release.Replace('\\','/'))+"; status=$?; exit \"$status\"";
 var creator=Start(operations,"creator",control,bash,args[3],new[]{"--noprofile","--norc","-c",script},cwdA,env,sidA,a,45000,request);UInt32[] ids=Ready(creator,ready);process=OpenProcess(0x121000,false,ids[0]);thread=OpenThread(0x120800,false,ids[1]);Need(process!=IntPtr.Zero&&thread!=IntPtr.Zero&&GetProcessIdOfThread(thread)==ids[0],"held-process-thread-identity");Need(WaitForSingleObject(process,0)==258&&WaitForSingleObject(thread,0)==258,"objects-alive-before-peers");String user=WindowsIdentity.GetCurrent().User.Value;Byte[] processSd=Security(process,user,a),threadSd=Security(thread,user,a);
 var same=Start(operations,"same",control,executable,args[1],new[]{"same",a,ids[0].ToString(),ids[1].ToString()},cwdA,env,sidA,a,6000);var sameResult=Complete(same,8000);var other=Start(operations,"other",control,executable,args[1],new[]{"other",b,ids[0].ToString(),ids[1].ToString()},cwdB,env,sidB,b,6000);var otherResult=Complete(other,8000);Need(WaitForSingleObject(process,0)==258&&WaitForSingleObject(thread,0)==258,"objects-alive-after-peers");Need(Security(process,user,a).SequenceEqual(processSd)&&Security(thread,user,a).SequenceEqual(threadSd),"effective-security-unchanged");ExclusiveMarker(release,"release\n");var creatorResult=Complete(creator,7000);Need(creatorResult.ObservedJobMembers>=2&&WaitForSingleObject(process,1000)==0&&WaitForSingleObject(thread,1000)==0,"Bash-child-and-thread-completed");Need(Hash(executable)==args[1]&&Hash(bash)==args[3]&&Hash(dll)==args[5],"unchanged-bound-inputs");proof="{\"schemaVersion\":1,\"packageA\":\""+a+"\",\"packageB\":\""+b+"\",\"pid\":"+ids[0]+",\"tid\":"+ids[1]+",\"sameProfileOpens\":12,\"otherProfileDenied\":12,\"drainedJobs\":3,\"processSecurityBase64\":\""+Convert.ToBase64String(processSd)+"\",\"threadSecurityBase64\":\""+Convert.ToBase64String(threadSd)+"\",\"creatorBase64\":\""+creatorResult.StdoutBase64+"\",\"sameBase64\":\""+sameResult.StdoutBase64+"\",\"otherBase64\":\""+otherResult.StdoutBase64+"\"}";
 }catch(Exception error){failure=error;}finally{drained=DrainAll(operations);if(drained){if(thread!=IntPtr.Zero)CloseHandle(thread);if(process!=IntPtr.Zero)CloseHandle(process);if(createdB&&WindowsAppContainerNative.DeleteAppContainerProfile(nameB)!=0)failure=new InvalidOperationException("delete-B",failure);if(createdA&&WindowsAppContainerNative.DeleteAppContainerProfile(nameA)!=0)failure=new InvalidOperationException("delete-A",failure);if(sidB!=IntPtr.Zero)WindowsAppContainerNative.FreeSid(sidB);if(sidA!=IntPtr.Zero)WindowsAppContainerNative.FreeSid(sidA);}else{Retained.Add(operations);Console.Error.WriteLine("retained-profiles:"+nameA+":"+nameB);failure=new InvalidOperationException("APPCONTAINER_CLEANUP_UNCONFIRMED",failure);}}
 if(failure!=null){Console.Error.WriteLine(failure);foreach(var operation in operations)if(operation.Result!=null)Console.Error.WriteLine("operation:"+operation.Name+":stdout:"+operation.Result.StdoutBase64+":stderr:"+operation.Result.StderrBase64);return 1;}Need(drained&&proof!=null,"completed-proof");Console.Write(proof);return 0;}
}
