/* Real process/thread opens only. Never changes a token or object descriptor. */
#include <windows.h>
#include <sddl.h>
#include <cstdio>
#include <cstdint>
#include <string>
#include <stdexcept>
#include <cwchar>
#include <cstring>
namespace {
void need(bool ok,const char *why){if(!ok)throw std::runtime_error(why);}
struct Handle {HANDLE value=NULL;~Handle(){if(value&&value!=INVALID_HANDLE_VALUE)CloseHandle(value);}};
const DWORD process_masks[]={0x1000,0x400,0x410,0x1,0x20,0x8,0x40};
const DWORD thread_masks[]={0x800,0x40,0x10,0x2,0x20};
DWORD decimal(const wchar_t *text){need(text&&*text&&wcslen(text)<=10,"id-syntax");uint64_t result=0;for(auto p=text;*p;++p){need(*p>=L'0'&&*p<=L'9',"id-syntax");result=result*10+(*p-L'0');need(result<=0xffffffff,"id-range");}need(result>0,"id-zero");return static_cast<DWORD>(result);}
std::wstring package(){Handle token;need(OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token.value)!=FALSE,"primary-token");DWORD flag=0,length=0;need(GetTokenInformation(token.value,TokenIsAppContainer,&flag,sizeof flag,&length)&&length==sizeof flag&&flag==1,"private-primary-token");union {ULONG_PTR align;BYTE bytes[256];} data;need(GetTokenInformation(token.value,TokenAppContainerSid,data.bytes,sizeof data.bytes,&length)&&length>=sizeof(TOKEN_APPCONTAINER_INFORMATION)&&length<=sizeof data.bytes,"package-query");PSID sid=reinterpret_cast<TOKEN_APPCONTAINER_INFORMATION*>(data.bytes)->TokenAppContainer;uintptr_t begin=reinterpret_cast<uintptr_t>(data.bytes),at=reinterpret_cast<uintptr_t>(sid);need(at>=begin+sizeof(TOKEN_APPCONTAINER_INFORMATION)&&at-begin<=length-8,"package-pointer");DWORD size=GetSidLengthRequired(*(reinterpret_cast<BYTE*>(sid)+1));need(size<=SECURITY_MAX_SID_SIZE&&size<=length-(at-begin)&&IsValidSid(sid),"package-bounds");LPWSTR text=NULL;need(ConvertSidToStringSidW(sid,&text)!=FALSE,"package-text");std::wstring result(text);LocalFree(text);need(result.size()<192,"package-size");return result;}
void marker(const wchar_t *path,const std::string &value){Handle file;file.value=CreateFileW(path,GENERIC_WRITE,0,NULL,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,NULL);need(file.value!=INVALID_HANDLE_VALUE,"marker-create");DWORD written=0;need(WriteFile(file.value,value.data(),static_cast<DWORD>(value.size()),&written,NULL)&&written==value.size()&&FlushFileBuffers(file.value),"marker-write");}
bool released(const wchar_t *path){Handle file;file.value=CreateFileW(path,GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT,NULL);if(file.value==INVALID_HANDLE_VALUE){DWORD error=GetLastError();need(error==ERROR_FILE_NOT_FOUND||error==ERROR_SHARING_VIOLATION||error==ERROR_LOCK_VIOLATION,"release-open");return false;}BY_HANDLE_FILE_INFORMATION info;need(GetFileInformationByHandle(file.value,&info)&&!(info.dwFileAttributes&(FILE_ATTRIBUTE_REPARSE_POINT|FILE_ATTRIBUTE_DIRECTORY))&&info.nFileSizeHigh==0&&info.nFileSizeLow==8,"release-physical-bounds");char data[8];DWORD read=0;need(ReadFile(file.value,data,8,&read,NULL)&&read==8&&memcmp(data,"release\n",8)==0,"release-bytes");return true;}
void hold(const wchar_t *sid,const wchar_t *ready,const wchar_t *release){need(package()==sid,"holder-package");DWORD pid=GetCurrentProcessId(),tid=GetCurrentThreadId();std::string record=std::to_string(pid)+" "+std::to_string(tid)+"\n";marker(ready,record);ULONGLONG start=GetTickCount64();while(!released(release)){need(GetTickCount64()-start<45000,"hold-deadline");Sleep(10);}printf("holder:pid=%lu:tid=%lu:released\n",static_cast<unsigned long>(pid),static_cast<unsigned long>(tid));}
void peer(bool allowed,const wchar_t *sid,DWORD pid,DWORD tid){need(package()==sid,"peer-package");for(int kind=0;kind<2;++kind){size_t count=kind?5:7;for(size_t i=0;i<count;++i){DWORD mask=kind?thread_masks[i]:process_masks[i];Handle handle;handle.value=kind?OpenThread(mask,FALSE,tid):OpenProcess(mask,FALSE,pid);DWORD error=handle.value?0:GetLastError();need(allowed?(handle.value!=NULL&&error==0):(handle.value==NULL&&error==ERROR_ACCESS_DENIED),"exact-access-outcome");if(allowed&&i==0)need((kind?GetThreadId(handle.value):GetProcessId(handle.value))==(kind?tid:pid),"opened-object-identity");printf("open:kind=%s:access=%lu:allowed=%u:error=%lu\n",kind?"thread":"process",static_cast<unsigned long>(mask),allowed?1:0,static_cast<unsigned long>(error));}}puts(allowed?"same:12:passed":"other:12:passed");}
}
int wmain(int argc,wchar_t **argv){try{if(argc==2&&std::wstring(argv[1])==L"host-check"){need(decimal(L"4294967295")==0xffffffff,"decimal-control");puts("host-check:passed");}else if(argc==5&&std::wstring(argv[1])==L"hold")hold(argv[2],argv[3],argv[4]);else if(argc==5&&(std::wstring(argv[1])==L"same"||std::wstring(argv[1])==L"other"))peer(std::wstring(argv[1])==L"same",argv[2],decimal(argv[3]),decimal(argv[4]));else throw std::runtime_error("arguments");return 0;}catch(const std::exception &error){fprintf(stderr,"process-security-refused:%s\n",error.what());return 1;}}
