'use strict'
const fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const p=require('../portable-runtime/portable.cjs')
function binary(dll,imports){ // Synthetic PE structure. No machine code, never executed.
 const b=Buffer.alloc(2048);b.writeUInt16LE(0x5a4d);b.writeUInt32LE(64,60);b.writeUInt32LE(0x4550,64);b.writeUInt16LE(0x8664,68);b.writeUInt16LE(1,70);b.writeUInt16LE(240,84);b.writeUInt16LE(2|(dll?0x2000:0),86);b.writeUInt16LE(0x20b,88);b.writeUInt32LE(2,196);b.writeUInt32LE(0x1000,208);b.writeUInt32LE((imports.length+1)*20,212);b.writeUInt32LE(0x1000,340);b.writeUInt32LE(1536,344);b.writeUInt32LE(512,348);for(let i=0;i<imports.length;i++){b.writeUInt32LE(0x1200+i*64,512+i*20+12);b.write(imports[i]+'\0',1024+i*64,'ascii')}return b
}
function setup(t){const root=fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(),'portable-candidate-test-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const build=path.join(root,'build');fs.mkdirSync(build);const files=new Map(Object.keys(p.MAP).map(key=>[key,Buffer.from(key+'\n')]));const tools={gcc:Buffer.from('owned gcc fixture'),ld:Buffer.from('owned ld fixture'),bootstrap:Buffer.from('owned runtime fixture'),archive:Buffer.from('owned source archive fixture')};files.set('runtime/bash.exe',binary(false,['kernel32.dll','msys-2.0.dll','user32.dll']));files.set('runtime/msys-2.0.dll',binary(true,['kernel32.dll','ntdll.dll']));files.set('fixture/posix-proof.exe',binary(false,['kernel32.dll','msys-2.0.dll']));
 const b={sdkCommit:'a'.repeat(40),sourceCommit:'b'.repeat(40),sourceArchiveSha256:p.hash(tools.archive),lockSha256:'0'.repeat(64),patchSha256:p.hash(files.get('evidence/adaptation.patch')),buildRecipeSha256:p.hash(files.get('evidence/build.sh')),posixRecipeSha256:p.hash(files.get('evidence/compile-posix-fixture.sh')),posixSourceSha256:p.hash(files.get('fixture/posix-proof.c')),gccSha256:p.hash(tools.gcc),linkerSha256:p.hash(tools.ld),bootstrapRuntimeSha256:p.hash(tools.bootstrap),bashSha256:p.hash(files.get('runtime/bash.exe'))};
 const lock={schema:1,sdk:{commit:b.sdkCommit,compilerSha256:b.gccSha256,compilerTarget:'x86_64-pc-cygwin',configureBuild:'x86_64-pc-cygwin'},source:{commit:b.sourceCommit,sha256:b.sourceArchiveSha256}};files.set('evidence/lock.json',p.canonical(lock));b.lockSha256=p.hash(files.get('evidence/lock.json'));
 files.set('evidence/adaptation.sha256',Buffer.from(b.patchSha256+'  adaptation.patch\n'));const receipt=Buffer.from(b.gccSha256+'  /usr/bin/gcc.exe\n'+b.linkerSha256+'  /usr/bin/ld.exe\n');files.set('evidence/toolchain-inputs.sha256',receipt);files.set('evidence/toolchain-outputs.sha256',Buffer.from(receipt));files.set('evidence/compiler-target.raw.txt',Buffer.from('x86_64-pc-cygwin\n'));files.set('evidence/bootstrap-runtime.sha256',Buffer.from(b.bootstrapRuntimeSha256+'  /usr/bin/msys-2.0.dll\n'));files.set('fixture/fixture.sha256',Buffer.from(b.posixSourceSha256+'  posix-proof.c\n'+p.hash(files.get('fixture/posix-proof.exe'))+'  posix-proof.exe\n'));
 files.set('evidence/stage.sha256',Buffer.from([['usr/bin/msys-2.0.dll','runtime/msys-2.0.dll'],['lock.json','evidence/lock.json'],['compiler.txt','evidence/compiler.txt'],['linker.txt','evidence/linker.txt'],['installed-packages.txt','evidence/installed-packages.txt'],['toolchain-inputs.sha256','evidence/toolchain-inputs.sha256'],['toolchain-outputs.sha256','evidence/toolchain-outputs.sha256']].map(([name,key])=>p.hash(files.get(key))+' *stage/'+name+'\n').join('')));
 const write=(name,bytes)=>{const file=path.join(build,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes)};for(const [name,bytes]of files)write(p.MAP[name],bytes);for(const [name,bytes]of [['sdk/usr/bin/gcc.exe',tools.gcc],['sdk/usr/bin/ld.exe',tools.ld],['sdk/usr/bin/msys-2.0.dll',tools.bootstrap],['sdk/issue27-build/source.tar.gz',tools.archive]])write(name,bytes);
 const expected={bindings:b,producer:{repository:'example/repository',headSha:'c'.repeat(40),runId:'123',runAttempt:1,jobId:'456',architecture:'x64'}};return{root,build,expected,files,packet:path.join(root,'packet'),dest:path.join(root,'imported')}
}

module.exports={setup}
