'use strict'
const fs = require('node:fs'), crypto = require('node:crypto'), assert = require('node:assert/strict'), { checksum, pe, dynamicBaseOnly } = require('./run.cjs')
const pinnedDll = '8960254d07105436cc2fce93d716790dd2ef31213c476e7c097fae41870dad80', pinnedBash = '5490d0da5e7cf9d92068cc48fcc590f2bcf8564add8ff91c3b5fe541eb2d72e3', sha = value => crypto.createHash('sha256').update(value).digest('hex')
const bytes = Buffer.alloc(1024); bytes.writeUInt16LE(0x5a4d, 0); bytes.writeUInt32LE(0x80, 0x3c); bytes.writeUInt32LE(0x4550, 0x80); bytes.writeUInt16LE(1, 0x86); bytes.writeUInt16LE(0xf0, 0x94); const optional = 0x98; bytes.writeUInt16LE(0x20b, optional); bytes.writeBigUInt64LE(0x210040000n, optional + 24); bytes.writeUInt32LE(0x200, optional + 64); bytes.writeUInt16LE(0, optional + 70); bytes.write('.data\0\0\0', optional + 0xf0, 'ascii'); bytes.writeUInt32LE(0x20d000, optional + 0xf0 + 12)
assert.equal(pe(bytes).dataRva, 0x20d000); const result = dynamicBaseOnly(bytes); assert.equal(pe(result.patched).dllCharacteristics, 0x40); assert.equal(result.patched.readUInt32LE(pe(result.patched).checksumOffset), checksum(Buffer.from(result.patched), pe(result.patched).checksumOffset));
const bashBytes = Buffer.from(bytes); bashBytes.writeUInt16LE(0x8000, optional + 70); const bashResult = dynamicBaseOnly(bashBytes, 0x8000, false); assert.equal(pe(bashResult.patched, false).dllCharacteristics, 0x8040); assert.equal(bashResult.patched.readUInt32LE(pe(bashResult.patched, false).checksumOffset), checksum(Buffer.from(bashResult.patched), pe(bashResult.patched, false).checksumOffset));
if (process.argv.length >= 3) { const actual = fs.readFileSync(process.argv[2]); assert.equal(sha(actual), pinnedDll, 'authenticated CI38 candidate DLL'); const actualPe = pe(actual), actualPatched = dynamicBaseOnly(actual, 0); assert.equal(actualPe.dataRva, 0x20d000, 'candidate .data RVA'); assert.equal(actualPatched.changed.length >= 2, true); if (process.argv.length === 4) { const bash = fs.readFileSync(process.argv[3]); assert.equal(sha(bash), pinnedBash, 'authenticated CI38 candidate Bash'); const bashPe = pe(bash, false), patchedBash = dynamicBaseOnly(bash, 0x8000, false); assert.equal(bashPe.imageBase, 0x100400000n); assert.equal(pe(patchedBash.patched, false).dllCharacteristics, 0x8040); } }
else assert.equal(process.argv.length, 2, 'Usage: node test-pe.cjs [PACKET/runtime/msys-2.0.dll [PACKET/runtime/bash.exe]]')
assert.ok(process.argv.length <= 4, 'Too many arguments')
console.log('PE DYNAMIC_BASE-only copies validated')
