// Diagnostic-only controller.  It deliberately retains failures as observations.
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.InteropServices;
using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;

public static class MappingController {
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern Boolean ConvertStringSecurityDescriptorToSecurityDescriptor(String text,UInt32 revision,out IntPtr descriptor,out UInt32 size);
 [DllImport("advapi32.dll",SetLastError=true)] static extern Boolean GetSecurityDescriptorSacl(IntPtr descriptor,out Boolean present,out IntPtr sacl,out Boolean defaulted);
 [DllImport("advapi32.dll",CharSet=CharSet.Unicode)] static extern UInt32 SetNamedSecurityInfo(String name,Int32 type,UInt32 flags,IntPtr owner,IntPtr group,IntPtr dacl,IntPtr sacl);
 [DllImport("kernel32.dll")] static extern IntPtr LocalFree(IntPtr memory);
 [DllImport("kernel32.dll",SetLastError=true)] static extern IntPtr OpenProcess(UInt32 access,Boolean inherit,UInt32 id);
 [DllImport("kernel32.dll",SetLastError=true)] static extern Boolean CloseHandle(IntPtr handle);
 [DllImport("kernel32.dll",SetLastError=true)] static extern Boolean GetProcessMitigationPolicy(IntPtr process,Int32 policy,out AslrPolicy buffer,IntPtr length);
 [DllImport("psapi.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern Boolean EnumProcessModulesEx(IntPtr process,IntPtr[] modules,UInt32 bytes,out UInt32 needed,UInt32 filter);
 [DllImport("psapi.dll",CharSet=CharSet.Unicode,SetLastError=true)] static extern UInt32 GetModuleFileNameEx(IntPtr process,IntPtr module,StringBuilder text,UInt32 capacity);
 [StructLayout(LayoutKind.Sequential)] struct AslrPolicy { public UInt32 Flags; }
 sealed class Observation { public UInt32 pid; public String path,bashPath; public UInt64 moduleBase,bashBase; public Int32 moduleError,bashError; public UInt32 aslrFlags; public Int32 aslrError; }
 sealed class Launch { public String cancel; public Task<WindowsAppContainerNative.LaunchResult> task; }
 static readonly List<Object> Retained=new List<Object>();
 static void Need(Boolean value,String reason){if(!value)throw new InvalidOperationException(reason);}
 static String Hash(String file){using(var stream=File.OpenRead(file))using(var hash=SHA256.Create())return BitConverter.ToString(hash.ComputeHash(stream)).Replace("-","").ToLowerInvariant();}
 static String Json(String value){if(value==null)return "null";var outp=new StringBuilder("\"");foreach(Char c in value){if(c=='\\'||c=='\"')outp.Append('\\').Append(c);else if(c=='\n')outp.Append("\\n");else if(c=='\r')outp.Append("\\r");else if(c=='\t')outp.Append("\\t");else if(c<32)outp.Append("\\u").Append(((Int32)c).ToString("x4"));else outp.Append(c);}return outp.Append('\"').ToString();}
 static String Shell(String value){return "'"+value.Replace("'","'\\''")+"'";}
 static void Marker(String path,String text){using(var s=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None)){Byte[] b=Encoding.ASCII.GetBytes(text);s.Write(b,0,b.Length);s.Flush(true);}}
 static void PrivateDirectory(String directory){
  var user=WindowsIdentity.GetCurrent().User;var security=new DirectorySecurity();security.SetOwner(user);security.SetAccessRuleProtection(true,false);
  security.AddAccessRule(new FileSystemAccessRule(user,FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));
  security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier("S-1-5-18"),FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));
  new DirectoryInfo(directory).SetAccessControl(security);
 }
 static void LowLabel(String directory){IntPtr sd=IntPtr.Zero,sacl;try{UInt32 size;Boolean present,defaulted;Need(ConvertStringSecurityDescriptorToSecurityDescriptor("S:(ML;;NW;;;LW)",1,out sd,out size),"low-descriptor");Need(GetSecurityDescriptorSacl(sd,out present,out sacl,out defaulted)&&present,"low-sacl");Need(SetNamedSecurityInfo(directory,1,0x10,IntPtr.Zero,IntPtr.Zero,IntPtr.Zero,sacl)==0,"low-label");}finally{if(sd!=IntPtr.Zero)LocalFree(sd);}}
 static void DirectoryAcl(String directory,String package,Boolean writable){
  PrivateDirectory(directory);var security=new DirectorySecurity();security.SetOwner(WindowsIdentity.GetCurrent().User);security.SetAccessRuleProtection(true,false);
  foreach(String sid in new[]{WindowsIdentity.GetCurrent().User.Value,"S-1-5-18"})security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));
  security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(package),writable?FileSystemRights.Modify:FileSystemRights.ReadAndExecute,writable?InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit:InheritanceFlags.None,PropagationFlags.None,AccessControlType.Allow));
  new DirectoryInfo(directory).SetAccessControl(security);if(writable)LowLabel(directory);
 }
 static void FileAcl(String file,String package){var user=WindowsIdentity.GetCurrent().User;var security=new FileSecurity();security.SetOwner(user);security.SetAccessRuleProtection(true,false);foreach(String sid in new[]{user.Value,"S-1-5-18"})security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(sid),FileSystemRights.FullControl,AccessControlType.Allow));security.AddAccessRule(new FileSystemAccessRule(new SecurityIdentifier(package),FileSystemRights.ReadAndExecute,AccessControlType.Allow));new FileInfo(file).SetAccessControl(security);}
 static String[] EnvironmentEntries(String bin,String comm){String root=Environment.GetEnvironmentVariable("SystemRoot"),local=Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);Need(!String.IsNullOrEmpty(root)&&!String.IsNullOrEmpty(local),"windows-folders");return new[]{"SystemRoot="+root,"WINDIR="+root,"SystemDrive="+root.Substring(0,2),"PATH="+bin,"LOCALAPPDATA="+local,"TEMP="+comm,"TMP="+comm,"MSYSTEM=MINGW64","CHERE_INVOKING=1"};}
 static Launch Start(String bash,String bashHash,String cwd,String[] env,IntPtr sid,String sidText,String cancel,WindowsAppContainerNative.MsysNamespaceRequest request,String script){Need(!File.Exists(cancel),"fresh-cancel");var result=new Launch{cancel=cancel};result.task=Task.Factory.StartNew(()=>WindowsAppContainerNative.Launch(bash,bashHash,new[]{"--noprofile","--norc","-c",script},cwd,env,90000,65536,sid,sidText,cancel,request),CancellationToken.None,TaskCreationOptions.LongRunning,TaskScheduler.Default);return result;}
 static UInt32 Ready(Launch launch,String ready){var clock=System.Diagnostics.Stopwatch.StartNew();while(true){if(File.Exists(ready)){try{using(var s=new FileStream(ready,FileMode.Open,FileAccess.Read,FileShare.Read)){Need(s.Length>=2&&s.Length<=16,"ready-length");Byte[] b=new Byte[(Int32)s.Length];Need(s.Read(b,0,b.Length)==b.Length,"ready-read");String text=Encoding.ASCII.GetString(b);UInt32 pid;Need(UInt32.TryParse(text.Trim(),out pid)&&pid>0,"ready-winpid");return pid;}}catch(IOException){}}
   Need(!launch.task.IsCompleted,"bash-exited-before-ready");Need(clock.ElapsedMilliseconds<20000,"ready-timeout");Thread.Sleep(10);}}
 static Observation Observe(UInt32 pid,String bash,String dll){var result=new Observation{pid=pid,path=null,bashPath=null,moduleBase=0,bashBase=0,moduleError=0,bashError=0,aslrFlags=0,aslrError=0};IntPtr process=OpenProcess(0x0410,false,pid);if(process==IntPtr.Zero){result.moduleError=Marshal.GetLastWin32Error();result.bashError=result.moduleError;result.aslrError=result.moduleError;return result;}try{
   AslrPolicy policy;if(GetProcessMitigationPolicy(process,1,out policy,(IntPtr)Marshal.SizeOf(typeof(AslrPolicy))))result.aslrFlags=policy.Flags;else result.aslrError=Marshal.GetLastWin32Error();
   IntPtr[] modules=new IntPtr[512];UInt32 needed;if(!EnumProcessModulesEx(process,modules,(UInt32)(modules.Length*IntPtr.Size),out needed,3)){result.moduleError=Marshal.GetLastWin32Error();return result;}if(needed>(UInt32)(modules.Length*IntPtr.Size)){result.moduleError=122;return result;}
   for(Int32 i=0;i<(Int32)(needed/(UInt32)IntPtr.Size);i++){var text=new StringBuilder(32768);UInt32 size=GetModuleFileNameEx(process,modules[i],text,(UInt32)text.Capacity);if(size==0||size>=text.Capacity)continue;String path=text.ToString();if(String.Equals(Path.GetFullPath(path),dll,StringComparison.OrdinalIgnoreCase)){result.path=path;result.moduleBase=unchecked((UInt64)modules[i].ToInt64());}else if(String.Equals(Path.GetFullPath(path),bash,StringComparison.OrdinalIgnoreCase)){result.bashPath=path;result.bashBase=unchecked((UInt64)modules[i].ToInt64());}}
   if(result.path==null)result.moduleError=126;if(result.bashPath==null)result.bashError=126;
  }finally{CloseHandle(process);}return result;}
 static String ChildErrors(String stderr,UInt64 dataRva){var matches=Regex.Matches(stderr??"",@"dll data read copy failed, 0x([0-9A-Fa-f]+)\.\.0x([0-9A-Fa-f]+), done ([0-9]+), windows pid ([0-9]+), Win32 error 299");var output=new StringBuilder("[");for(Int32 i=0;i<matches.Count;i++){var m=matches[i];UInt64 start=Convert.ToUInt64(m.Groups[1].Value,16),end=Convert.ToUInt64(m.Groups[2].Value,16);if(i>0)output.Append(',');output.Append("{\"start\":\"").Append(start.ToString("x")).Append("\",\"end\":\"").Append(end.ToString("x")).Append("\",\"childBase\":").Append(start>=dataRva?Json("0x"+(start-dataRva).ToString("x")):"null").Append(",\"pid\":").Append(m.Groups[4].Value).Append('}');}return output.Append(']').ToString();}
 static String Script(String ready,String release,String before,String child,String after) { return "set -euo pipefail; printf 'mapping-start\\n'; printf 'mapping-stderr-start\\n' >&2; if ! IFS= read -r pid < /proc/self/winpid; then exit 125; fi; printf '%s\\n' \"$pid\" > "+Shell(ready.Replace('\\','/'))+"; while [[ ! -e "+Shell(release.Replace('\\','/'))+" ]]; do :; done; printf 'mapping-before\\n'; printf 'before:%s\\n' \"$pid\" > "+Shell(before.Replace('\\','/'))+"; x=$(IFS= read -r child_pid < /proc/self/winpid; printf '%s\\n' \"$child_pid\" > "+Shell(child.Replace('\\','/'))+"; printf child); IFS= read -r after_pid < /proc/self/winpid; printf '%s:%s\\n' \"$after_pid\" \"$x\" > "+Shell(after.Replace('\\','/'))+"; printf 'mapping-child=%s\\n' \"$x\""; }
 static String ProbeScript(String ready,String release,String before,String child,String after,String helper,String witness) {
  String original=Script(ready,release,before,child,after);
  String needle="; printf child)";Need(original.Contains(needle),"probe-script-anchor");
  return original.Replace(needle,"; exec "+Shell(helper.Replace('\\','/'))+" "+Shell(witness.Replace('\\','/'))+")");
 }
 static String Witness(String path,Int32 maximum=128) {
  FileAttributes attributes;
  try { attributes=File.GetAttributes(path); } catch(FileNotFoundException) { return "{\"present\":false}"; }
  Need((attributes&(FileAttributes.ReparsePoint|FileAttributes.Directory))==0,"witness-physical-file");
  using(var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)) {
   Need(stream.Length<=maximum,"witness-bound");Byte[] bytes=new Byte[(Int32)stream.Length];Int32 used=0;
   while(used<bytes.Length){Int32 count=stream.Read(bytes,used,bytes.Length-used);Need(count>0,"witness-short-read");used+=count;}
   Need(stream.ReadByte()==-1,"witness-grew");return "{\"present\":true,\"base64\":"+Json(Convert.ToBase64String(bytes))+"}";
  }
 }
 static Boolean Drain(Launch launch){if(!launch.task.IsCompleted){try{Marker(launch.cancel,"cancel\n");}catch(IOException){if(!File.Exists(launch.cancel))return false;}}try{return launch.task.Wait(12000)&&launch.task.GetAwaiter().GetResult().Drained;}catch{return false;}}
 public static Int32 Main(String[] args){IntPtr sid=IntPtr.Zero;Boolean profile=false,drained=false,released=false,cleanupConfirmed=false;Launch launch=null;Observation observed=null;WindowsAppContainerNative.LaunchResult completed=null;Exception failure=null;String output=null,profileName=null,releasePath=null,outputPath=null;try{
  Need(args.Length==8||args.Length==10,"args: bash bash-sha dll dll-sha shared-id data-rva-hex work label");String bash=Path.GetFullPath(args[0]),bashHash=args[1],dll=Path.GetFullPath(args[2]),dllHash=args[3],shared=args[4],work=Path.GetFullPath(args[6]),label=args[7];UInt64 dataRva=Convert.ToUInt64(args[5],16);Need(Hash(bash)==bashHash&&Hash(dll)==dllHash,"bound-inputs");Directory.CreateDirectory(work);String control=Path.Combine(work,"control"),comm=Path.Combine(work,"communications"),ready=Path.Combine(comm,"ready"),release=Path.Combine(comm,"release");Directory.CreateDirectory(control);Directory.CreateDirectory(comm);Need(!File.Exists(ready)&&!File.Exists(release),"fresh-markers");
  String helper=args.Length==10?Path.GetFullPath(args[8]):null,helperHash=args.Length==10?args[9]:null;Need(helper==null||Hash(helper)==helperHash,"bound-helper");
  String bin=Path.GetDirectoryName(bash),usr=Path.GetDirectoryName(bin),runtime=Path.GetDirectoryName(usr),etc=Path.Combine(runtime,"etc");Need(Path.GetFileName(bin).Equals("bin",StringComparison.OrdinalIgnoreCase)&&Path.GetFileName(usr).Equals("usr",StringComparison.OrdinalIgnoreCase)&&File.Exists(Path.Combine(etc,"fstab")),"runtime-layout");
  profileName="Autoprompt_"+Guid.NewGuid().ToString("N");Need(WindowsAppContainerNative.CreateAppContainerProfile(profileName,profileName,profileName,IntPtr.Zero,0,out sid)>=0,"profile-create");profile=true;String package=new SecurityIdentifier(sid).Value;DirectoryAcl(runtime,package,false);DirectoryAcl(usr,package,false);DirectoryAcl(bin,package,false);DirectoryAcl(etc,package,false);FileAcl(bash,package);FileAcl(dll,package);if(helper!=null){Need(Path.GetDirectoryName(helper)==bin,"helper-runtime-path");FileAcl(helper,package);}FileAcl(Path.Combine(etc,"fstab"),package);DirectoryAcl(comm,package,true);releasePath=release;
  var request=new WindowsAppContainerNative.MsysNamespaceRequest{DllPath=dll,DllSha256=dllHash,SharedId=shared};String before=Path.Combine(comm,"before"),child=Path.Combine(comm,"child"),after=Path.Combine(comm,"after");
  String probeWitness=Path.Combine(comm,"pipe-probe");String script=helper==null?Script(ready,release,before,child,after):ProbeScript(ready,release,before,child,after,helper,probeWitness);
  launch=Start(bash,bashHash,comm,EnvironmentEntries(bin,comm),sid,package,Path.Combine(control,"cancel"),request,script);UInt32 observedPid=Ready(launch,ready);observed=Observe(observedPid,bash,dll);Need(observed.moduleError==0&&observed.path!=null&&observed.moduleBase!=0&&String.Equals(Path.GetFullPath(observed.path),Path.GetFullPath(dll),StringComparison.OrdinalIgnoreCase),"loaded-dll-path-mismatch");Need(observed.aslrError==0,"aslr-policy-query");Marker(release,"release\n");released=true;Need(launch.task.Wait(95000),"launch-timeout");completed=launch.task.GetAwaiter().GetResult();drained=completed.Drained;Need(drained&&completed.RootImageMatches&&!completed.TimedOut&&!completed.Cancelled&&!completed.OutputLimit,"launcher-drain");Need(completed.RootPid==observedPid,"winpid-rootpid-match");String stderr=Encoding.UTF8.GetString(Convert.FromBase64String(completed.StderrBase64)),stdout=Encoding.UTF8.GetString(Convert.FromBase64String(completed.StdoutBase64)),errors=ChildErrors(stderr,dataRva);Boolean success=completed.ExitCode==0&&stdout=="mapping-start\nmapping-before\nmapping-child=child\n"&&stderr=="mapping-stderr-start\n";String classification=success?"success":errors!="[]"?"fork-error-299":"unexpected";
  String witnesses="{\"before\":"+Witness(before)+",\"child\":"+Witness(child)+",\"after\":"+Witness(after)+"}";
  Need(Hash(bash)==bashHash&&Hash(dll)==dllHash&&(helper==null||Hash(helper)==helperHash),"inputs-changed");output="{\"schemaVersion\":1,\"status\":\"observed-not-accepted\",\"label\":"+Json(label)+",\"bashSha256\":"+Json(bashHash)+",\"msysSha256\":"+Json(dllHash)+",\"dataRva\":"+Json("0x"+dataRva.ToString("x"))+",\"observedWinPid\":"+observedPid+",\"rootPid\":"+completed.RootPid+",\"module\":{\"path\":"+Json(observed.path)+",\"base\":"+(observed.path==null?"null":Json("0x"+observed.moduleBase.ToString("x")))+",\"error\":"+observed.moduleError+"},\"bashModule\":{\"path\":"+Json(observed.bashPath)+",\"base\":"+(observed.bashPath==null?"null":Json("0x"+observed.bashBase.ToString("x")))+",\"error\":"+observed.bashError+"},\"aslr\":{\"flags\":"+observed.aslrFlags+",\"error\":"+observed.aslrError+"},\"launch\":{\"exitCode\":"+completed.ExitCode+",\"drained\":true,\"rootImageMatches\":true,\"observedJobMembers\":"+completed.ObservedJobMembers+",\"classification\":"+Json(classification)+"},\"pipeProbe\":"+(helper==null?"null":Witness(probeWitness,4096))+",\"helperSha256\":"+Json(helperHash)+",\"witnesses\":"+witnesses+",\"childDataErrors\":"+errors+",\"stdoutBase64\":"+Json(completed.StdoutBase64)+",\"stderrBase64\":"+Json(completed.StderrBase64)+"}";outputPath=Path.Combine(work,label+".json");
 }catch(Exception e){failure=e;}finally{if(launch!=null&&!released&&releasePath!=null){try{Marker(releasePath,"release\n");}catch(IOException){}}if(launch!=null)drained=Drain(launch);if(profile&&(launch==null||drained)){Int32 deleted=WindowsAppContainerNative.DeleteAppContainerProfile(profileName);if(deleted!=0)failure=new InvalidOperationException("profile-delete:"+deleted,failure);else if(sid!=IntPtr.Zero&&WindowsAppContainerNative.FreeSid(sid)!=IntPtr.Zero)failure=new InvalidOperationException("FreeSid",failure);else cleanupConfirmed=true;}if(!drained&&launch!=null)Retained.Add(new Object[]{launch,sid,profileName});}
 if(failure!=null){if(observed!=null)Console.Error.WriteLine("mapping-observation={\"winPid\":"+observed.pid+",\"modulePath\":"+Json(observed.path)+",\"moduleBase\":"+(observed.moduleBase==0?"null":Json("0x"+observed.moduleBase.ToString("x")))+",\"moduleError\":"+observed.moduleError+",\"bashPath\":"+Json(observed.bashPath)+",\"bashBase\":"+(observed.bashBase==0?"null":Json("0x"+observed.bashBase.ToString("x")))+",\"bashError\":"+observed.bashError+",\"aslrFlags\":"+observed.aslrFlags+",\"aslrError\":"+observed.aslrError+"}");if(completed==null&&launch!=null&&launch.task.Status==TaskStatus.RanToCompletion)completed=launch.task.GetAwaiter().GetResult();if(completed!=null)Console.Error.WriteLine("mapping-launch={\"exitCode\":"+completed.ExitCode+",\"drained\":"+(completed.Drained?"true":"false")+",\"timedOut\":"+(completed.TimedOut?"true":"false")+",\"cancelled\":"+(completed.Cancelled?"true":"false")+",\"outputLimit\":"+(completed.OutputLimit?"true":"false")+",\"rootPid\":"+completed.RootPid+",\"stdoutBase64\":"+Json(completed.StdoutBase64)+",\"stderrBase64\":"+Json(completed.StderrBase64)+"}");else if(launch!=null&&launch.task.IsFaulted)Console.Error.WriteLine("mapping-launch-task="+launch.task.Exception);Console.Error.WriteLine(failure);return 1;}Need(cleanupConfirmed,"cleanup-unconfirmed");output=output.Substring(0,output.Length-1)+",\"cleanupConfirmed\":true}";File.WriteAllText(outputPath,output+"\n",new UTF8Encoding(false));Console.WriteLine(output);return 0; }
}
