'use strict'
// Candidate transport only. Never launches a binary, admits a runtime, or writes a smoke pass receipt.
const fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto'), assert = require('node:assert/strict')
const MAX_FILE = 16 * 1024 * 1024, MAX_TOTAL = 32 * 1024 * 1024, MAX_META = 1024 * 1024
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex')
const MAP = Object.freeze({
  'runtime/bash.exe': 'sdk/usr/bin/bash.exe',
  'runtime/msys-2.0.dll': 'sdk/issue27-build/stage/usr/bin/msys-2.0.dll',
  'fixture/posix-proof.exe': 'sdk/issue27-build/posix-compile-fixture/posix-proof.exe',
  'fixture/posix-proof.c': 'sdk/issue27-build/posix-compile-fixture/posix-proof.c',
  'fixture/fixture.sha256': 'sdk/issue27-build/posix-compile-fixture/fixture.sha256',
  'evidence/lock.json': 'sdk/issue27-build/stage/lock.json',
  'evidence/adaptation.patch': 'sdk/issue27-build/adaptation.patch',
  'evidence/adaptation.sha256': 'sdk/issue27-build/adaptation.sha256',
  'evidence/stage.sha256': 'sdk/issue27-build/stage.sha256',
  'evidence/toolchain-inputs.sha256': 'sdk/issue27-build/toolchain-inputs.sha256',
  'evidence/toolchain-outputs.sha256': 'sdk/issue27-build/toolchain-outputs.sha256',
  'evidence/compiler.txt': 'sdk/issue27-build/compiler.txt',
  'evidence/linker.txt': 'sdk/issue27-build/linker.txt',
  'evidence/compiler-target.raw.txt': 'sdk/issue27-build/compiler-target.raw.txt',
  'evidence/bootstrap-runtime.sha256': 'sdk/issue27-build/bootstrap-runtime.sha256',
  'evidence/installed-packages.txt': 'sdk/issue27-build/installed-packages.txt',
  'evidence/build-flags.txt': 'sdk/issue27-build/build-flags.txt',
  'evidence/build.sh': 'sdk/issue27-build/build.sh',
  'evidence/compile-posix-fixture.sh': 'sdk/issue27-build/posix-fixture/compile-posix-fixture.sh',
})
const BINDINGS = ['sdkCommit','sourceCommit','sourceArchiveSha256','lockSha256','patchSha256','buildRecipeSha256','posixRecipeSha256','posixSourceSha256','gccSha256','linkerSha256','bootstrapRuntimeSha256','bashSha256']
const exact = (value, keys) => { assert.ok(value && typeof value === 'object' && !Array.isArray(value)); assert.deepEqual(Object.keys(value).sort(), [...keys].sort()) }
function canonical(value) { function sort(x) { if (x === null || ['string','boolean'].includes(typeof x)) return x; if (typeof x === 'number') { assert.ok(Number.isSafeInteger(x)); return x } if (Array.isArray(x)) return x.map(sort); assert.ok(x && typeof x === 'object' && [Object.prototype, null].includes(Object.getPrototypeOf(x))); return Object.fromEntries(Object.keys(x).sort().map(key => [key, sort(x[key])])) } return Buffer.from(JSON.stringify(sort(value)) + '\n') }
function parseCanonical(bytes) { assert.ok(Buffer.isBuffer(bytes) && bytes.length <= MAX_META); const text = bytes.toString('utf8'); assert.ok(Buffer.from(text).equals(bytes)); const value = JSON.parse(text); assert.ok(canonical(value).equals(bytes), 'Noncanonical or duplicate-key manifest'); return value }
function relative(name) { assert.equal(typeof name, 'string'); assert.ok(name.length > 0 && name.length <= 256 && name.split('/').every(part => part.length <= 96 && /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/.test(part) && !/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/.test(part)), 'Unsafe packet path'); return name }
function physical(file, directory = false) { assert.ok(path.isAbsolute(file), 'Absolute path required'); const full = path.resolve(file); assert.equal(fs.realpathSync.native(full), full, 'Aliased physical path'); for (let cursor = full;; cursor = path.dirname(cursor)) { const st = fs.lstatSync(cursor); assert.ok(!st.isSymbolicLink(), 'Symbolic link refused'); if (cursor !== full || directory) assert.ok(st.isDirectory(), 'Directory required'); if (cursor === path.dirname(cursor)) break } return full }
function read(file, maximum = MAX_FILE) { file = physical(file); const fd = fs.openSync(file, fs.constants.O_RDONLY | (fs.constants.O_NOFOLLOW || 0)); try { const before = fs.fstatSync(fd, { bigint: true }); assert.ok(before.isFile() && before.nlink === 1n && before.size > 0n && before.size <= BigInt(maximum), 'Unbounded, empty or hardlinked file'); const bytes = Buffer.alloc(Number(before.size)); let used = 0; while (used < bytes.length) { const n = fs.readSync(fd, bytes, used, bytes.length - used, null); assert.ok(n > 0, 'Short read'); used += n } assert.equal(fs.readSync(fd, Buffer.alloc(1), 0, 1, null), 0, 'File grew'); const after = fs.fstatSync(fd, { bigint: true }), current = fs.lstatSync(file, { bigint: true }); for (const key of ['dev','ino','size','mtimeNs','ctimeNs','nlink']) { assert.equal(after[key], before[key], 'File changed during capture'); assert.equal(current[key], before[key], 'Path replaced during capture') } return bytes } finally { fs.closeSync(fd) } }
function authority(value) { value = JSON.parse(canonical(value)); exact(value, ['bindings','producer']); exact(value.bindings, BINDINGS); for (const [key, digest] of Object.entries(value.bindings)) assert.match(digest, key.endsWith('Commit') ? /^[a-f0-9]{40}$/ : /^[a-f0-9]{64}$/); const p = value.producer; exact(p, ['repository','headSha','runId','runAttempt','jobId','architecture']); assert.match(p.repository, /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/); assert.match(p.headSha, /^[a-f0-9]{40}$/); for (const key of ['runId','jobId']) assert.match(p[key], /^[1-9][0-9]{0,19}$/); assert.ok(Number.isSafeInteger(p.runAttempt) && p.runAttempt >= 1 && p.runAttempt <= 10000); assert.equal(p.architecture, 'x64'); return value }
function inventory(files) { let total = 0; const entries = [...files].map(([name, bytes]) => { relative(name); assert.ok(Buffer.isBuffer(bytes) && bytes.length > 0 && bytes.length <= MAX_FILE); total += bytes.length; return { path: name, length: bytes.length, sha256: hash(bytes) } }).sort((a,b) => a.path < b.path ? -1 : a.path > b.path ? 1 : 0); assert.ok(total <= MAX_TOTAL && entries.length <= 32); assert.equal(new Set(entries.map(entry => entry.path)).size, entries.length); return entries }
function list(root) { physical(root, true); const found = []; const directories = []; let count = 0; function visit(relativeRoot) { for (const name of fs.readdirSync(path.join(root, relativeRoot))) { assert.ok(++count <= 64, 'Closed tree entry bound'); const key = relativeRoot ? relativeRoot + '/' + name : name; relative(key); const st = fs.lstatSync(path.join(root, key)); assert.ok(!st.isSymbolicLink(), 'Linked packet entry'); if (st.isDirectory()) { directories.push(key); visit(key) } else { assert.ok(st.isFile() && st.nlink === 1, 'Nonregular packet entry'); found.push(key) } } } visit(''); const expectedDirs = new Set(); for (const name of found) { let parent = path.posix.dirname(name); while (parent !== '.') { expectedDirs.add(parent); parent = path.posix.dirname(parent) } } assert.deepEqual(directories.sort(), [...expectedDirs].sort(), 'Extra empty directory refused'); return found.sort() }
function pe(bytes, dll) { assert.ok(bytes.length >= 90 && bytes.readUInt16LE(0) === 0x5a4d, 'DOS header'); const at = bytes.readUInt32LE(60); assert.ok(at >= 64 && at <= bytes.length - 26); assert.equal(bytes.readUInt32LE(at), 0x4550); assert.equal(bytes.readUInt16LE(at + 4), 0x8664, 'Expected x64 MSYS binary'); const sections = bytes.readUInt16LE(at + 6), optional = bytes.readUInt16LE(at + 20), flags = bytes.readUInt16LE(at + 22); assert.ok(sections > 0 && sections <= 96 && optional >= 112 && at + 24 + optional + sections * 40 <= bytes.length); assert.equal(bytes.readUInt16LE(at + 24), 0x20b); assert.ok(flags & 2); assert.equal(Boolean(flags & 0x2000), dll, 'PE role mismatch') }
function checksums(bytes, prefix = '') { assert.ok(bytes.length <= MAX_META); const text = bytes.toString('ascii'); assert.ok(Buffer.from(text, 'ascii').equals(bytes) && text.endsWith('\n') && !text.includes('\r')); const records = new Map(), seen = new Set(); for (const line of text.slice(0,-1).split('\n')) { const m = /^([a-f0-9]{64}) [ *]([^\0]+)$/.exec(line); assert.ok(m, 'Malformed checksum record'); const name = m[2]; assert.ok(name.startsWith(prefix)); const local = name.slice(prefix.length); assert.ok(local.split('/').every(part => /^[A-Za-z0-9_+.-]+$/.test(part) && part !== '.' && part !== '..'), 'Checksum path escape'); assert.ok(!seen.has(name.toLowerCase()), 'Checksum alias'); seen.add(name.toLowerCase()); records.set(name, m[1]); assert.ok(records.size <= 2048) } return records }
function validate(files, expected) { assert.deepEqual([...files.keys()].sort(), Object.keys(MAP).sort(), 'Exact candidate inventory'); inventory(files); const b = expected.bindings, get = key => { const bytes = files.get(key); assert.ok(bytes); return bytes }, bind = (key, digest) => assert.equal(hash(get(key)), digest, 'Authority mismatch: ' + key)
  for (const [key, field] of [['runtime/bash.exe','bashSha256'],['fixture/posix-proof.c','posixSourceSha256'],['evidence/lock.json','lockSha256'],['evidence/adaptation.patch','patchSha256'],['evidence/build.sh','buildRecipeSha256'],['evidence/compile-posix-fixture.sh','posixRecipeSha256']]) bind(key,b[field])
  const lock = JSON.parse(get('evidence/lock.json')); assert.equal(lock.schema,1); assert.equal(lock.sdk.commit,b.sdkCommit); assert.equal(lock.sdk.compilerSha256,b.gccSha256); assert.equal(lock.sdk.compilerTarget,'x86_64-pc-cygwin'); assert.equal(lock.sdk.configureBuild,'x86_64-pc-cygwin'); assert.equal(lock.source.commit,b.sourceCommit); assert.equal(lock.source.sha256,b.sourceArchiveSha256)
  assert.equal(get('evidence/adaptation.sha256').toString(), b.patchSha256 + '  adaptation.patch\n')
  const tools = checksums(get('evidence/toolchain-inputs.sha256'), '/usr/bin/'); assert.deepEqual([...tools.keys()], ['/usr/bin/gcc.exe','/usr/bin/ld.exe']); assert.equal(tools.get('/usr/bin/gcc.exe'),b.gccSha256); assert.equal(tools.get('/usr/bin/ld.exe'),b.linkerSha256); assert.ok(get('evidence/toolchain-inputs.sha256').equals(get('evidence/toolchain-outputs.sha256')), 'Compiler/linker changed')
  assert.match(get('evidence/compiler-target.raw.txt').toString(), /^x86_64-pc-cygwin\r?\n$/)
  const bootstrap = checksums(get('evidence/bootstrap-runtime.sha256'), '/usr/bin/'); assert.deepEqual([...bootstrap.keys()], ['/usr/bin/msys-2.0.dll']); assert.equal(bootstrap.get('/usr/bin/msys-2.0.dll'), b.bootstrapRuntimeSha256)
  const fixture = checksums(get('fixture/fixture.sha256')); assert.deepEqual([...fixture.keys()], ['posix-proof.c','posix-proof.exe']); assert.equal(fixture.get('posix-proof.c'), b.posixSourceSha256); assert.equal(fixture.get('posix-proof.exe'),hash(get('fixture/posix-proof.exe')))
  const stage = checksums(get('evidence/stage.sha256'), 'stage/'); for (const [stageName, key] of [['usr/bin/msys-2.0.dll','runtime/msys-2.0.dll'],['lock.json','evidence/lock.json'],['compiler.txt','evidence/compiler.txt'],['linker.txt','evidence/linker.txt'],['installed-packages.txt','evidence/installed-packages.txt'],['toolchain-inputs.sha256','evidence/toolchain-inputs.sha256'],['toolchain-outputs.sha256','evidence/toolchain-outputs.sha256']]) assert.equal(stage.get('stage/'+stageName),hash(get(key)), 'Stage receipt mismatch: '+stageName)
  pe(get('runtime/bash.exe'),false); pe(get('runtime/msys-2.0.dll'),true); pe(get('fixture/posix-proof.exe'),false)
  const { importedDlls } = require('./pe.cjs')
  for (const [file, expectedImports] of [['runtime/bash.exe',['kernel32.dll','msys-2.0.dll','user32.dll']],['runtime/msys-2.0.dll',['kernel32.dll','ntdll.dll']],['fixture/posix-proof.exe',['kernel32.dll','msys-2.0.dll']]]) assert.deepEqual(importedDlls(get(file)),expectedImports,'Unexpected compiled dependency closure')
}
function createFresh(destination, files, native) { destination = path.resolve(destination); physical(path.dirname(destination),true); assert.equal(fs.existsSync(destination),false,'Fresh destination required'); fs.mkdirSync(destination,{ mode:0o700 }); if (process.platform === 'win32') { assert.ok(native && typeof native.privateAcl === 'function','Native private ACL provider required'); native.privateAcl(destination) } for (const [name, bytes] of files) { relative(name); const parent = path.dirname(path.join(destination,name)); fs.mkdirSync(parent,{recursive:true,mode:0o700}); physical(parent,true); fs.writeFileSync(path.join(destination,name),bytes,{flag:'wx',mode:0o600}) } return destination }
async function capture(root, entries, native) { assert.deepEqual(list(root),entries.map(entry=>entry.path).sort(),'Packet inventory differs'); let result; if (process.platform === 'win32') { assert.ok(native && typeof native.capture === 'function','Native held-file lease required'); result = await native.capture(root, entries.map(entry=>({...entry}))); assert.ok(Array.isArray(result)); result = new Map(result.map(entry=>[entry.path,Buffer.from(entry.bytes)])) } else { result = new Map(entries.map(entry=>[entry.path,read(path.join(root,entry.path))])) } assert.deepEqual(inventory(result),entries); assert.deepEqual(list(root),entries.map(entry=>entry.path).sort(),'Packet changed after capture'); return result }
async function exportCandidate({ buildRoot, expected, destination, native }) { expected=authority(expected); buildRoot=physical(path.resolve(buildRoot),true); const files = new Map(Object.entries(MAP).map(([name,input])=>[name,read(path.join(buildRoot,input))])); validate(files,expected)
  assert.equal(hash(read(path.join(buildRoot,'sdk/issue27-build/source.tar.gz'),128*1024*1024)),expected.bindings.sourceArchiveSha256)
  for(const [name,key] of [['gcc.exe','gccSha256'],['ld.exe','linkerSha256'],['msys-2.0.dll','bootstrapRuntimeSha256']]) assert.equal(hash(read(path.join(buildRoot,'sdk/usr/bin',name))),expected.bindings[key], 'Current SDK tool differs from build receipt')
  const manifest = {schema:1,kind:'msys-candidate-transport',status:'not-native-accepted',authority:expected,architecture:{bash:'x64',msys:'x64',posixFixture:'x64'},files:inventory(files)}
  const bytes=canonical(manifest); files.set('manifest.json',bytes); const root=createFresh(destination,files,native); await capture(root,inventory(files),native)
  return Object.freeze({root,manifestSha256:hash(bytes),status:'candidate-exported-not-accepted'})
}
async function importCandidate({ packetRoot, manifestSha256, expected, destination, native }) { assert.match(manifestSha256,/^[a-f0-9]{64}$/); expected=authority(expected); packetRoot=physical(path.resolve(packetRoot),true)
  const manifestBytes=read(path.join(packetRoot,'manifest.json'),MAX_META); assert.equal(hash(manifestBytes),manifestSha256,'External manifest authority mismatch'); const manifest=parseCanonical(manifestBytes); exact(manifest,['schema','kind','status','authority','architecture','files']); assert.equal(manifest.schema,1); assert.equal(manifest.kind,'msys-candidate-transport'); assert.equal(manifest.status,'not-native-accepted'); assert.deepEqual(authority(manifest.authority),expected); assert.deepEqual(manifest.architecture,{bash:'x64',msys:'x64',posixFixture:'x64'})
  assert.ok(Array.isArray(manifest.files)&&manifest.files.length===Object.keys(MAP).length); let total=0; const names=new Set(); for(const entry of manifest.files){exact(entry,['path','length','sha256']);relative(entry.path);assert.ok(!names.has(entry.path));names.add(entry.path);assert.ok(Number.isSafeInteger(entry.length)&&entry.length>0&&entry.length<=MAX_FILE);total+=entry.length;assert.match(entry.sha256,/^[a-f0-9]{64}$/)} assert.ok(total+manifestBytes.length<=MAX_TOTAL); assert.deepEqual([...names].sort(),Object.keys(MAP).sort())
  const entries=[...manifest.files,{path:'manifest.json',length:manifestBytes.length,sha256:manifestSha256}].sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0)
  const captured=await capture(packetRoot,entries,native); assert.ok(captured.get('manifest.json').equals(manifestBytes)); const files=new Map(captured);files.delete('manifest.json');validate(files,expected)
  const receipt={schema:1,kind:'msys-candidate-import',status:'not-native-accepted',manifestSha256,producer:expected.producer,consumer:{platform:process.platform,processArchitecture:process.arch},files:manifest.files,nativeAcceptance:'not-performed'}
  captured.set('import.json',canonical(receipt));const root=createFresh(destination,captured,native);await capture(root,inventory(captured),native)
  return Object.freeze({root,receiptSha256:hash(captured.get('import.json')),manifestSha256,status:'candidate-imported-not-accepted'})
}
module.exports={exportCandidate,importCandidate,canonical,parseCanonical,authority,relative,read,checksums,pe,validate,MAP,hash,MAX_FILE,MAX_TOTAL}
