'use strict'
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const p=require('./portable.cjs')
function binary(dll,imports){ // Synthetic PE structure. No machine code, never executed.
 const b=Buffer.alloc(2048);b.writeUInt16LE(0x5a4d);b.writeUInt32LE(64,60);b.writeUInt32LE(0x4550,64);b.writeUInt16LE(0x8664,68);b.writeUInt16LE(1,70);b.writeUInt16LE(240,84);b.writeUInt16LE(2|(dll?0x2000:0),86);b.writeUInt16LE(0x20b,88);b.writeUInt32LE(2,196);b.writeUInt32LE(0x1000,208);b.writeUInt32LE((imports.length+1)*20,212);b.writeUInt32LE(0x1000,340);b.writeUInt32LE(1536,344);b.writeUInt32LE(512,348);for(let i=0;i<imports.length;i++){b.writeUInt32LE(0x1200+i*64,512+i*20+12);b.write(imports[i]+'\0',1024+i*64,'ascii')}return b
}
function setup(t){const root=fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(),'portable-candidate-test-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const build=path.join(root,'build');fs.mkdirSync(build);const files=new Map(Object.keys(p.MAP).map(key=>[key,Buffer.from(key+'\n')]));const tools={gcc:Buffer.from('owned gcc fixture'),ld:Buffer.from('owned ld fixture'),bootstrap:Buffer.from('owned runtime fixture'),archive:Buffer.from('owned source archive fixture')};files.set('runtime/bash.exe',binary(false,['kernel32.dll','msys-2.0.dll','user32.dll']));files.set('runtime/msys-2.0.dll',binary(true,['kernel32.dll','ntdll.dll']));files.set('fixture/posix-proof.exe',binary(false,['kernel32.dll','msys-2.0.dll']));
 const b={sdkCommit:'a'.repeat(40),sourceCommit:'b'.repeat(40),sourceArchiveSha256:p.hash(tools.archive),lockSha256:'0'.repeat(64),patchSha256:p.hash(files.get('evidence/adaptation.patch')),buildRecipeSha256:p.hash(files.get('evidence/build.sh')),posixRecipeSha256:p.hash(files.get('evidence/compile-posix-fixture.sh')),posixSourceSha256:p.hash(files.get('fixture/posix-proof.c')),gccSha256:p.hash(tools.gcc),linkerSha256:p.hash(tools.ld),bootstrapRuntimeSha256:p.hash(tools.bootstrap),bashSha256:p.hash(files.get('runtime/bash.exe'))};
 const lock={schema:1,sdk:{commit:b.sdkCommit,compilerSha256:b.gccSha256,compilerTarget:'x86_64-pc-cygwin',configureBuild:'x86_64-pc-cygwin'},source:{commit:b.sourceCommit,sha256:b.sourceArchiveSha256}};files.set('evidence/lock.json',p.canonical(lock));b.lockSha256=p.hash(files.get('evidence/lock.json'));
 files.set('evidence/adaptation.sha256',Buffer.from(b.patchSha256+'  adaptation.patch\n'));const receipt=Buffer.from(b.gccSha256+'  /usr/bin/gcc.exe\n'+b.linkerSha256+'  /usr/bin/ld.exe\n');files.set('evidence/toolchain-inputs.sha256',receipt);files.set('evidence/toolchain-outputs.sha256',Buffer.from(receipt));files.set('evidence/compiler-target.raw.txt',Buffer.from('x86_64-pc-cygwin\n'));files.set('evidence/bootstrap-runtime.sha256',Buffer.from(b.bootstrapRuntimeSha256+'  /usr/bin/msys-2.0.dll\n'));files.set('fixture/fixture.sha256',Buffer.from(b.posixSourceSha256+'  posix-proof.c\n'+p.hash(files.get('fixture/posix-proof.exe'))+'  posix-proof.exe\n'));
 files.set('evidence/stage.sha256',Buffer.from([['usr/bin/msys-2.0.dll','runtime/msys-2.0.dll'],['lock.json','evidence/lock.json'],['compiler.txt','evidence/compiler.txt'],['linker.txt','evidence/linker.txt'],['installed-packages.txt','evidence/installed-packages.txt'],['toolchain-inputs.sha256','evidence/toolchain-inputs.sha256'],['toolchain-outputs.sha256','evidence/toolchain-outputs.sha256']].map(([name,key])=>p.hash(files.get(key))+' *stage/'+name+'\n').join('')));
 const write=(name,bytes)=>{const file=path.join(build,name);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,bytes)};for(const [name,bytes]of files)write(p.MAP[name],bytes);for(const [name,bytes]of [['sdk/usr/bin/gcc.exe',tools.gcc],['sdk/usr/bin/ld.exe',tools.ld],['sdk/usr/bin/msys-2.0.dll',tools.bootstrap],['sdk/issue27-build/source.tar.gz',tools.archive]])write(name,bytes);
 const expected={bindings:b,producer:{repository:'example/repository',headSha:'c'.repeat(40),runId:'123',runAttempt:1,jobId:'456',architecture:'x64'}};return{root,build,expected,files,packet:path.join(root,'packet'),dest:path.join(root,'imported')}
}
async function exported(t){const x=setup(t);const receipt=await p.exportCandidate({buildRoot:x.build,expected:x.expected,destination:x.packet});return{...x,receipt}}
async function importOne(x,changes={}){return p.importCandidate({packetRoot:x.packet,manifestSha256:x.receipt.manifestSha256,expected:x.expected,destination:x.dest,...changes})}
function rewrittenManifest(x,change){const file=path.join(x.packet,'manifest.json');const value=JSON.parse(fs.readFileSync(file));change(value);const bytes=p.canonical(value);fs.writeFileSync(file,bytes);return p.hash(bytes)}
test('export/import creates only a fresh candidate receipt; never acceptance or producer absolute paths',async t=>{const x=await exported(t),result=await importOne(x);assert.equal(result.status,'candidate-imported-not-accepted');const receipt=JSON.parse(fs.readFileSync(path.join(x.dest,'import.json')));assert.equal(receipt.nativeAcceptance,'not-performed');assert.equal(receipt.status,'not-native-accepted');assert.ok(!fs.readFileSync(path.join(x.dest,'manifest.json'),'utf8').includes(x.build));assert.equal(fs.existsSync(path.join(x.dest,'built-runtime-proof.txt')),false);assert.deepEqual(fs.readFileSync(path.join(x.dest,'runtime/msys-2.0.dll')),x.files.get('runtime/msys-2.0.dll'))})
for(const name of ['runtime/bash.exe','runtime/msys-2.0.dll','fixture/posix-proof.exe','evidence/lock.json','evidence/adaptation.patch','evidence/toolchain-inputs.sha256'])test('captured bytes mutation refused: '+name,async t=>{const x=await exported(t);fs.appendFileSync(path.join(x.packet,name),'mutated');await assert.rejects(importOne(x));assert.equal(fs.existsSync(x.dest),false)})
for(const [name,change]of [['source identity',m=>m.authority.bindings.sourceCommit='d'.repeat(40)],['producer head',m=>m.authority.producer.headSha='d'.repeat(40)],['producer run',m=>m.authority.producer.runId='124'],['extra manifest key',m=>m.accepted=true],['native acceptance claim',m=>m.status='accepted'],['wrong architecture',m=>m.architecture.msys='arm64'],['traversal',m=>m.files[0].path='../escape'],['absolute path',m=>m.files[0].path='/outside'],['NTFS stream',m=>m.files[0].path='runtime/bash.exe:stream'],['device',m=>m.files[0].path='runtime/nul.exe'],['case alias',m=>m.files[0].path='Runtime/Bash.exe'],['missing entry',m=>m.files.pop()],['duplicate entry',m=>m.files[1]=m.files[0]],['oversized entry',m=>m.files[0].length=64*1024*1024]])test('externally rehashed invalid manifest refused: '+name,async t=>{const x=await exported(t);const digest=rewrittenManifest(x,change);await assert.rejects(importOne(x,{manifestSha256:digest}));assert.equal(fs.existsSync(x.dest),false)})
for(const mode of ['extra file','extra empty directory','hardlink','symlink','linked parent','missing file'])test('physical closed inventory refuses '+mode,async t=>{const x=await exported(t);const file=path.join(x.packet,'runtime/bash.exe');if(mode==='extra file')fs.writeFileSync(path.join(x.packet,'extra'),'x');if(mode==='extra empty directory')fs.mkdirSync(path.join(x.packet,'extra'));if(mode==='missing file')fs.unlinkSync(file);if(mode==='hardlink')fs.linkSync(file,path.join(x.root,'outside-hardlink'));if(mode==='symlink'){fs.renameSync(file,path.join(x.root,'outside'));fs.symlinkSync(path.join(x.root,'outside'),file)}if(mode==='linked parent'){fs.renameSync(path.join(x.packet,'runtime'),path.join(x.root,'runtime'));fs.symlinkSync(path.join(x.root,'runtime'),path.join(x.packet,'runtime'),'dir')}await assert.rejects(importOne(x));assert.equal(fs.existsSync(x.dest),false)})
test('wrong external manifest digest is refused',async t=>{const x=await exported(t);await assert.rejects(importOne(x,{manifestSha256:'0'.repeat(64)}))})
test('noncanonical and duplicate JSON keys are refused even with supplied matching digest',async t=>{const x=await exported(t);const file=path.join(x.packet,'manifest.json');const bytes=Buffer.from(fs.readFileSync(file,'utf8').replace('{','{"schema":1,'));fs.writeFileSync(file,bytes);await assert.rejects(importOne(x,{manifestSha256:p.hash(bytes)}))})
test('fresh destination refuses preexisting content without overwriting it',async t=>{const x=await exported(t);fs.mkdirSync(x.dest);fs.writeFileSync(path.join(x.dest,'user-file'),'keep');await assert.rejects(importOne(x));assert.equal(fs.readFileSync(path.join(x.dest,'user-file'),'utf8'),'keep')})
for(const [name,file]of [['changed linker after build','sdk/usr/bin/ld.exe'],['changed GCC after build','sdk/usr/bin/gcc.exe'],['changed source archive','sdk/issue27-build/source.tar.gz'],['missing toolchain receipt','sdk/issue27-build/toolchain-outputs.sha256']])test('export refuses '+name,async t=>{const x=setup(t);if(name.startsWith('missing'))fs.unlinkSync(path.join(x.build,file));else fs.appendFileSync(path.join(x.build,file),'mutated');await assert.rejects(p.exportCandidate({buildRoot:x.build,expected:x.expected,destination:x.packet}));assert.equal(fs.existsSync(x.packet),false)})
test('unexpected dynamic dependency is refused despite internally consistent stage checksums',t=>{const x=setup(t);const bytes=binary(true,['evil.dll','kernel32.dll']);x.files.set('runtime/msys-2.0.dll',bytes);const text=x.files.get('evidence/stage.sha256').toString().replace(/^[a-f0-9]{64}( \*stage\/usr\/bin\/msys-2.0.dll)/,p.hash(bytes)+'$1');x.files.set('evidence/stage.sha256',Buffer.from(text));assert.throws(()=>p.validate(x.files,x.expected),/dependency/)})
